/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misOfertasDesktopUI;

import MisOfertasDesktopEntities.Producto;
import MisOfertasDesktopEntities.Rubro;
import java.awt.event.ActionListener;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.DatePicker;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import misOfertasDesktopDAO.*;

/**
 *
 * @author David
 */
public class mantenedorProductos extends javax.swing.JFrame {

    /**
     * Creates new form initFrame
     */
    public mantenedorProductos() {
        initComponents();
        populateTable();
        populateComboBox();
        jTextFieldIdProductoEdit.setEditable(false);
        jDateChooserAddProducto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGroupProdPerecibleAdd = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddProducto = new javax.swing.JButton();
        jButtonEditProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdProductoEdit = new javax.swing.JTextField();
        jTextFieldNombreProdEdit = new javax.swing.JTextField();
        jTextFieldNombreRubro = new javax.swing.JTextField();
        jTextFieldPerecible = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNombreAdd = new javax.swing.JTextField();
        jCheckBoxProductoPerecible = new javax.swing.JCheckBox();
        jComboBoxRubro = new javax.swing.JComboBox<>();
        jDateChooserAddProducto = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdministrar = new javax.swing.JMenu();
        jMenuItemProducto = new javax.swing.JMenuItem();
        jMenuItemTienda = new javax.swing.JMenuItem();
        jMenuItemRubro = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Rubro", "¿Activo?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonAddProducto.setText("Agregar");
        jButtonAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductoActionPerformed(evt);
            }
        });

        jButtonEditProducto.setText("Guardar");
        jButtonEditProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Editar producto");

        jLabel2.setText("ID Producto");

        jLabel3.setText("Nombre Producto");

        jLabel4.setText("Rubro");

        jLabel5.setText("¿Producto perecible?");

        jTextFieldIdProductoEdit.setEditable(false);

        jTextFieldNombreRubro.setEditable(false);

        jTextFieldPerecible.setEditable(false);

        jLabel6.setText("Agregar Producto");

        jLabel7.setText("Nombre Producto");

        jLabel8.setText("¿Producto Perecible?");

        jLabel9.setText("Fecha Vencimiento");

        jLabel10.setText("Rubro");

        jTextFieldNombreAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreAddActionPerformed(evt);
            }
        });

        jCheckBoxProductoPerecible.setText("Si");
        jCheckBoxProductoPerecible.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxProductoPerecibleItemStateChanged(evt);
            }
        });
        jCheckBoxProductoPerecible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProductoPerecibleActionPerformed(evt);
            }
        });

        jComboBoxRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jButtonEditProducto)))
                                        .addGap(0, 99, Short.MAX_VALUE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNombreProdEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldNombreRubro)
                                            .addComponent(jTextFieldPerecible)
                                            .addComponent(jTextFieldIdProductoEdit)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(33, 33, 33)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreAdd)
                            .addComponent(jComboBoxRubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAddProducto)
                                    .addComponent(jCheckBoxProductoPerecible))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jDateChooserAddProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldIdProductoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNombreProdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNombreRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldPerecible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jButtonEditProducto)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNombreAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxProductoPerecible)
                            .addComponent(jLabel8))
                        .addGap(17, 17, 17)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserAddProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addComponent(jButtonAddProducto)
                .addGap(33, 33, 33))
        );

        jMenuAdministrar.setText("Administrar");

        jMenuItemProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appRepositorio/producto.png"))); // NOI18N
        jMenuItemProducto.setText("Productos");
        jMenuItemProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductoActionPerformed(evt);
            }
        });
        jMenuAdministrar.add(jMenuItemProducto);

        jMenuItemTienda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appRepositorio/store.png"))); // NOI18N
        jMenuItemTienda.setText("Tiendas");
        jMenuItemTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTiendaActionPerformed(evt);
            }
        });
        jMenuAdministrar.add(jMenuItemTienda);

        jMenuItemRubro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appRepositorio/rubro.png"))); // NOI18N
        jMenuItemRubro.setText("Rubros");
        jMenuAdministrar.add(jMenuItemRubro);

        jMenuItemUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appRepositorio/usuario.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuarios");
        jMenuAdministrar.add(jMenuItemUsuario);

        jMenuBar1.add(jMenuAdministrar);

        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemTiendaActionPerformed

    private void jMenuItemProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProductoActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        evt.paramString();
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        ProductoDAO pDAO = new ProductoDAO();
        Producto p = new Producto();
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());// TODO add your handling code here:
        int column = 0;
        String id = source.getModel().getValueAt(row, column).toString();
        p = pDAO.findById(Long.valueOf(id));
        jTextFieldIdProductoEdit.setText(String.valueOf(p.getIdProducto()));
        jTextFieldNombreProdEdit.setText(String.valueOf(p.getNombreProducto()));
        jTextFieldNombreRubro.setText(String.valueOf(p.getRubro().getNombreRubro()));
        if (p.getEsPerecible() == 2) {
            jTextFieldPerecible.setText("Si");
        } else {
            jTextFieldPerecible.setText("No");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductoActionPerformed
        ProductoDAO pDAO = new ProductoDAO();
        RubroDAO rDAO = new RubroDAO();
        Producto p = new Producto();
        try {
            Long idP = pDAO.getMaxId();
            p.setIdProducto(++idP);
            p.setNombreProducto(jTextFieldNombreAdd.getText());
            if (!jCheckBoxProductoPerecible.isSelected()) {
                p.setEsPerecible(1);
                p.setFechaVencimiento("N/A");
            } else {
                p.setEsPerecible(2);
                p.setFechaVencimiento(jDateChooserAddProducto.getDate().toString());
            }
            p.setRubro(rDAO.getRubroByName(jComboBoxRubro.getSelectedItem().toString()));
            pDAO.addProducto(p);
        } catch (Exception ex) {
            Logger.getLogger(mantenedorProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAddProductoActionPerformed

    private void jButtonEditProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditProductoActionPerformed
        ProductoDAO pDAO = new ProductoDAO();
        Producto p = new Producto();
        Rubro r = new Rubro();
        try {
            p = pDAO.findById(Long.valueOf(jTextFieldIdProductoEdit.getText()));
            p.setNombreProducto(jTextFieldNombreProdEdit.getText());
            pDAO.editProducto(p);

        } catch (Exception ex) {
            Logger.getLogger(mantenedorProductos.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            JOptionPane.showMessageDialog(null, "Producto con ID" + p.getIdProducto() + " actualizado correctamente.");

        }
        populateTable();
    }//GEN-LAST:event_jButtonEditProductoActionPerformed

    private void jCheckBoxProductoPerecibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProductoPerecibleActionPerformed


    }//GEN-LAST:event_jCheckBoxProductoPerecibleActionPerformed

    private void jCheckBoxProductoPerecibleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxProductoPerecibleItemStateChanged
        if (!jCheckBoxProductoPerecible.isSelected()) {
            jDateChooserAddProducto.setEnabled(false);
        } else {
            jDateChooserAddProducto.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBoxProductoPerecibleItemStateChanged

    private void jTextFieldNombreAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mantenedorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mantenedorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mantenedorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mantenedorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mantenedorProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProducto;
    private javax.swing.JButton jButtonEditProducto;
    private javax.swing.ButtonGroup jButtonGroupProdPerecibleAdd;
    private javax.swing.JCheckBox jCheckBoxProductoPerecible;
    private javax.swing.JComboBox<String> jComboBoxRubro;
    private com.toedter.calendar.JDateChooser jDateChooserAddProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAdministrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemProducto;
    private javax.swing.JMenuItem jMenuItemRubro;
    private javax.swing.JMenuItem jMenuItemTienda;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldIdProductoEdit;
    private javax.swing.JTextField jTextFieldNombreAdd;
    private javax.swing.JTextField jTextFieldNombreProdEdit;
    private javax.swing.JTextField jTextFieldNombreRubro;
    private javax.swing.JTextField jTextFieldPerecible;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        ProductoDAO pDAO = new ProductoDAO();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        List<Producto> lista = pDAO.listAll();
        Object rowData[] = new Object[4];
        for (Producto prod : lista) {
            rowData[0] = prod.getIdProducto();
            rowData[1] = prod.getNombreProducto();
            rowData[2] = prod.getRubro().getNombreRubro();
            rowData[3] = prod.getEsPerecible();
            model.addRow(rowData);
        }
    }

    private void populateComboBox() {
        RubroDAO rDAO = new RubroDAO();
        List<Rubro> lista = rDAO.listAll();
        jComboBoxRubro.removeAllItems();
        DefaultComboBoxModel defaultC = new DefaultComboBoxModel();
        for (Rubro r : lista) {
            defaultC.addElement(r.getNombreRubro());
        }
        jComboBoxRubro.setModel(defaultC);
    }

    private void refreshData() {
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
        m.setRowCount(0);
    }

    private void cargarTextbox(String id) {
    }
}
